"""change type for opinion

Revision ID: 78e744918768
Revises: 
Create Date: 2019-03-11 00:55:37.369554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e744918768'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('opinions', 'opinion',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.VARCHAR(length=3000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('type', sa.INTEGER(), nullable=True),
    sa.Column('country_id', sa.INTEGER(), nullable=True),
    sa.Column('state_id', sa.INTEGER(), nullable=True),
    sa.Column('city_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name='fk_schools_city_id_cities'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='fk_schools_country_id_countries'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], name='fk_schools_state_id_states'),
    sa.PrimaryKeyConstraint('id', name='pk_schools')
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), nullable=True),
    sa.Column('followed_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], name='fk_followers_followed_id_users'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='fk_followers_follower_id_users')
    )
    op.create_table('user_votes',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('poll_id', sa.INTEGER(), nullable=False),
    sa.Column('opinion', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['opinion'], ['opinions.id'], name='fk_user_votes_opinion_opinions'),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name='fk_user_votes_poll_id_polls'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_votes_user_id_users'),
    sa.PrimaryKeyConstraint('user_id', 'poll_id', 'opinion', name='pk_user_votes')
    )
    op.create_table('feeds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('num_of_subscribers', sa.INTEGER(), nullable=True),
    sa.Column('last_post_added', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_feeds')
    )
    op.create_table('states',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('state_code', sa.VARCHAR(length=255), nullable=True),
    sa.Column('country_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='fk_states_country_id_countries'),
    sa.PrimaryKeyConstraint('id', name='pk_states')
    )
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question_stmt', sa.TEXT(length=255), nullable=True),
    sa.Column('poser_id', sa.INTEGER(), nullable=True),
    sa.Column('explanation', sa.TEXT(length=255), nullable=True),
    sa.Column('date_edited', sa.DATETIME(), nullable=True),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.Column('votes', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['poser_id'], ['users.id'], name='fk_questions_poser_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_questions')
    )
    # ### end Alembic commands ###
